
import {
  ArrowRight,
  BrainCircuit,
  CheckCircle2,
  Clock,
  Code,
  Code2,
  LifeBuoy,
  Mail,
  MapPin,
  MousePointerClick,
  Palette,
  Phone,
  PhoneCall,
  Rocket,
  Search,
  ShieldCheck,
  Smartphone,
  Sparkles,
  TrendingUp,
  Zap,
} from "lucide-react";
import LeadForm from "@/components/blocks/LeadForm";
import { pageMetadata } from "@/lib/pageMeta";
import styles from "./websites.module.css";
import { Header, Reveal } from "./Chrome";

export const dynamic = "force-dynamic";

// ── /websites — the SiteDrop design, ported 1:1 into our architecture ────────────────────────
//
// The design was generated by SiteDrop ($2.50) and is carried by gradients, blurs, floating cards
// and a custom type scale. The Puck block system has no primitives for any of those, so importing
// it through lib/importHtml.ts would have flattened exactly what we bought. Decision 2026-07-30:
// SiteDrop supplies the DESIGN, SJC supplies the COPY, the TRUTH and the PLUMBING.
//
// ⚠️ THIS IS THE UNEDITED PORT. The copy below is still SiteDrop's generated placeholder text.
// Steven is editing it. Until he has, this page MUST NOT be deployed — see the list at the bottom
// of this comment.
//
// WHAT CHANGED FROM THE RAW HTML (plumbing only, no design):
//   • Tailwind CDN  -> the repo's own Tailwind v4
//   • Google Fonts <link> -> next/font (Space Grotesk and Inter are both in the global set now)
//   • Lucide CDN    -> lucide-react
//   • Supabase-hosted images -> /public (they lived on SiteDrop's storage and would 404 later)
//   • Its own <form> + fetch -> our shared LeadForm block, so a lead lands where every other
//     lead lands. This is the one piece that must never be re-implemented per page.
//
// ⚠️ BEFORE THIS GOES LIVE:
//   1. The founder photo (/sitedrop-founder.png) is a STOCK PHOTO OF A MAN WHO IS NOT STEVEN.
//   2. "10+ Years Building / 120+ Sites Shipped / 100% Hand-Coded" — invented.
//   3. "+284% Traffic Growth" and "100/100 PageSpeed" — invented.
//   4. Nav + footer link to #testimonials and #stats; neither section exists.
//   5. "Now Booking 2025 Projects" — it is 2026.
//   6. NO PRICE may appear on this page. Price lands on the discovery call.
//
// ⚠️ NO GLOBAL NAV. The site-wide header links to the free Skool community, which teaches what
// this page sells. The header in ./Chrome.tsx is deliberately self-contained.

// Space Grotesk is registered site-wide in app/layout.tsx (it joined the curated brand set), so
// --font-space-grotesk is already on <html>. Registering it again here would load the same font
// twice under two hashes.

const PHONE_DISPLAY = "(210) 851-4906";
const PHONE_HREF = "tel:+12108514906";

// ⚠️ THE og BLOCK IS LOAD-BEARING. Next.js inherits the ROOT layout's openGraph wholesale when a
// page has none, so a link texted to a groomer used to preview as "Your AI Growth Partner" — the
// AI-implementation business, not this one. lib/pageMeta.ts always emits the full block.
export async function generateMetadata() {
  return pageMetadata("websites", {
    path: "/websites",
    title: "A real website for your business — live in three days | Steven James Consulting",
    description:
      "Built and live in three days. Your work, your reviews, your phone number — and a contact form that texts you the second someone fills it out. You never touch any of it.",
    ogTitle: "A real website for your business — live in three days",
    ogDescription:
      "Your work, your reviews, your phone number — and a contact form that texts you the second someone fills it out. You never touch any of it.",
  });
}

const SERVICES = [
  {
    icon: Smartphone,
    title: "Mobile-First Design",
    body: "Pixel-perfect layouts that feel native on every phone, tablet, and desktop. Because 70% of your customers browse on their thumb.",
  },
  {
    icon: Search,
    title: "SEO & Google Optimization",
    body: "Technical SEO baked into every page. Schema markup, Core Web Vitals, keyword architecture — ranked, not buried.",
  },
  {
    icon: BrainCircuit,
    title: "AI-Ready Content",
    body: "Structured for ChatGPT, Perplexity, and Google AI Overviews. When customers ask AI for recommendations, your name comes up.",
  },
  {
    icon: MousePointerClick,
    title: "Conversion-Focused UX",
    body: "Every button, form, and headline is A/B-tested logic. We design flows that turn visitors into paying customers.",
  },
  {
    icon: Code2,
    title: "Custom Development",
    body: "No cookie-cutter templates. Hand-crafted code, custom integrations, and animations tailored to your brand identity.",
  },
  {
    icon: LifeBuoy,
    title: "Ongoing Support",
    body: "Your site stays fast, secure, and current. Monthly performance reports, updates, and a direct line to Steven.",
  },
];

const PROCESS = [
  {
    n: "01",
    icon: Search,
    title: "Discover",
    body: 'Deep-dive call. We audit your competitors, map your customer journey, and define what "winning" looks like for your business.',
  },
  {
    n: "02",
    icon: Palette,
    title: "Design",
    body: "Interactive mockups on mobile and desktop. You see every screen, every animation, every color choice — before a line of code.",
  },
  {
    n: "03",
    icon: Code,
    title: "Develop",
    body: "Custom-coded with performance in mind. SEO schema, AI-ready structure, and lightning-fast load times baked in from day one.",
  },
  {
    n: "04",
    icon: Rocket,
    title: "Deploy",
    body: "Launch day. We handle DNS, analytics, Google indexing, and training. Then we monitor traffic and iterate for growth.",
  },
];

const CONTACT_CARDS = [
  { icon: Phone, label: "Call Direct", value: `+1 ${PHONE_DISPLAY.replace(/[()]/g, "").replace(" ", "-")}`, href: PHONE_HREF },
  { icon: Clock, label: "Response Time", value: "Within 24 Hours" },
  { icon: ShieldCheck, label: "No Obligation", value: "100% Free Consultation" },
];

const FOOTER_SERVICES = [
  "Mobile-First Design",
  "SEO Optimization",
  "AI Content Architecture",
  "Custom Development",
  "Ongoing Support",
];

const FOOTER_COMPANY = [
  { href: "#about", label: "About Steven" },
  { href: "#process", label: "Our Process" },
  { href: "#testimonials", label: "Testimonials" },
  { href: "#stats", label: "Results" },
  { href: "#contact", label: "Contact" },
];

export default function WebsitesPage() {
  return (
    <div className={`${styles.page} bg-[#FAFAFA]`}>
      <Header />

      <main>
        {/* ── HERO ───────────────────────────────────────────────────────────── */}
        <section id="hero" className="relative overflow-hidden bg-[#0A0E27] py-20 md:py-28 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -left-32 top-0 h-[600px] w-[600px] animate-pulse rounded-full bg-[#00D9FF]/10 blur-[120px]" />
            <div className="absolute -right-32 bottom-0 h-[500px] w-[500px] rounded-full bg-[#1E293B] blur-[100px]" />
            <div className="absolute left-1/3 top-1/2 h-[400px] w-[400px] rounded-full bg-[#00D9FF]/5 blur-[100px]" />
            <div className={`absolute inset-0 opacity-[0.07] ${styles.grid60}`} />
          </div>

          <div className="relative mx-auto max-w-7xl px-6 sm:px-8">
            <div className="grid items-center gap-12 lg:grid-cols-12 lg:gap-8">
              <div className="lg:col-span-7">
                <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-[#00D9FF]/20 bg-[#00D9FF]/5 px-4 py-2 backdrop-blur-sm">
                  <span className="relative flex h-2 w-2">
                    <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-[#00D9FF] opacity-75" />
                    <span className="relative inline-flex h-2 w-2 rounded-full bg-[#00D9FF]" />
                  </span>
                  <span className="text-xs font-medium uppercase tracking-widest text-[#00D9FF]">
                    Now Booking 2025 Projects
                  </span>
                </div>

                <h1 className="text-5xl font-bold leading-[1.05] tracking-tight text-white md:text-6xl lg:text-7xl">
                  Websites That <br className="hidden sm:block" />
                  <span className="relative inline-block">
                    <span className="bg-linear-to-r from-[#00D9FF] via-[#00D9FF] to-white bg-clip-text text-transparent">
                      Win Everywhere.
                    </span>
                    <svg
                      className="absolute -bottom-2 left-0 w-full"
                      height="12"
                      viewBox="0 0 300 12"
                      fill="none"
                      preserveAspectRatio="none"
                      aria-hidden="true"
                    >
                      <path
                        d="M2 8 Q 75 2, 150 6 T 298 4"
                        stroke="#00D9FF"
                        strokeWidth="2"
                        strokeLinecap="round"
                        fill="none"
                        opacity="0.6"
                      />
                    </svg>
                  </span>
                </h1>

                <p className="mt-8 max-w-2xl text-lg leading-relaxed text-white/70 md:text-xl">
                  Steven James Consulting builds mobile-first websites engineered to rank on Google,
                  get discovered by AI search, and convert visitors into paying customers — all from
                  one custom-crafted digital home.
                </p>

                <div className="mt-10 flex flex-col items-start gap-4 sm:flex-row sm:items-center">
                  <a
                    href="#contact"
                    className="group inline-flex w-full items-center justify-center gap-2 rounded-full bg-[#00D9FF] px-8 py-4 text-sm font-semibold text-[#0A0E27] transition-all duration-300 hover:-translate-y-0.5 hover:shadow-2xl hover:shadow-[#00D9FF]/40 sm:w-auto"
                  >
                    Get Free Quote
                    <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                  </a>
                  <a
                    href={PHONE_HREF}
                    className="inline-flex w-full items-center justify-center gap-3 rounded-full border border-white/15 px-8 py-4 text-sm font-semibold text-white transition-all duration-300 hover:border-[#00D9FF]/50 hover:bg-white/5 sm:w-auto"
                  >
                    <PhoneCall className="h-4 w-4 text-[#00D9FF]" />
                    Call +1 210-851-4906
                  </a>
                </div>

                <div className="mt-12 flex flex-wrap items-center gap-x-8 gap-y-4 text-xs uppercase tracking-widest text-white/50">
                  <div className="flex items-center gap-2">
                    <Smartphone className="h-4 w-4 text-[#00D9FF]" />
                    Mobile-First
                  </div>
                  <div className="flex items-center gap-2">
                    <Search className="h-4 w-4 text-[#00D9FF]" />
                    Google-Optimized
                  </div>
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-[#00D9FF]" />
                    AI-Ready
                  </div>
                </div>
              </div>

              {/* Floating device mockup */}
              <div className="relative lg:col-span-5">
                <div className="relative mx-auto max-w-md">
                  <div className="absolute -inset-8 rounded-full bg-linear-to-br from-[#00D9FF]/30 to-transparent blur-3xl" />

                  <div className="relative rounded-[2.5rem] border border-white/10 bg-linear-to-br from-[#1E293B] to-[#0A0E27] p-3 shadow-2xl shadow-[#00D9FF]/10">
                    <div className="overflow-hidden rounded-[2rem] border border-white/5">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src="/sitedrop-hero.png"
                        alt="Modern responsive website design mockup displayed on a smartphone"
                        className="h-auto w-full object-cover"
                        width={1024}
                        height={1024}
                      />
                    </div>
                  </div>

                  <div
                    className="absolute -left-6 top-16 animate-bounce rounded-2xl border border-white/10 bg-white/5 p-4 shadow-2xl backdrop-blur-xl md:-left-12"
                    style={{ animationDuration: "4s" }}
                  >
                    <div className="flex items-center gap-3">
                      <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#00D9FF]/20">
                        <TrendingUp className="h-5 w-5 text-[#00D9FF]" />
                      </div>
                      <div>
                        <div className="text-lg font-bold leading-none text-white">+284%</div>
                        <div className="mt-1 text-xs text-white/50">Traffic Growth</div>
                      </div>
                    </div>
                  </div>

                  <div className="absolute -right-4 bottom-20 rounded-2xl border border-white/10 bg-white/5 p-4 shadow-2xl backdrop-blur-xl md:-right-10">
                    <div className="flex items-center gap-3">
                      <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#00D9FF]/20">
                        <Zap className="h-5 w-5 text-[#00D9FF]" />
                      </div>
                      <div>
                        <div className="text-lg font-bold leading-none text-white">100/100</div>
                        <div className="mt-1 text-xs text-white/50">PageSpeed Score</div>
                      </div>
                    </div>
                  </div>

                  <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 rounded-full border border-[#00D9FF]/30 bg-[#0A0E27] px-5 py-2 shadow-lg shadow-[#00D9FF]/10">
                    <div className="flex items-center gap-2">
                      <CheckCircle2 className="h-4 w-4 text-[#00D9FF]" />
                      <span className="text-xs font-medium text-white">Live &amp; Converting</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="pointer-events-none absolute bottom-0 left-0 right-0 h-24 bg-linear-to-t from-[#FAFAFA] to-transparent" />
        </section>

        {/* ── SERVICES ───────────────────────────────────────────────────────── */}
        <section id="services" className="relative overflow-hidden bg-[#0A0E27] py-20 md:py-28 lg:py-32">
          <div className="absolute inset-0 opacity-20">
            <div className="absolute left-1/4 top-0 h-96 w-96 rounded-full bg-[#00D9FF] blur-[120px]" />
            <div className="absolute bottom-0 right-1/4 h-96 w-96 rounded-full bg-[#00D9FF] opacity-50 blur-[150px]" />
          </div>

          <div className="relative z-10 mx-auto max-w-6xl px-6 sm:px-8">
            <Reveal className="mb-16 text-center">
              <span className="mb-6 inline-block rounded-full border border-[#00D9FF]/30 bg-[#00D9FF]/5 px-4 py-1.5 text-xs font-medium uppercase tracking-widest text-[#00D9FF]">
                What We Build
              </span>
              <h2 className="mb-6 text-4xl font-bold text-white md:text-5xl lg:text-6xl">
                Web Design Services
                <br />
                <span className="text-[#00D9FF]">Engineered to Convert</span>
              </h2>
              <p className="mx-auto max-w-2xl text-lg leading-relaxed text-slate-400">
                Every site we ship is built to dominate mobile screens, rank on Google, and get
                discovered by AI search engines like ChatGPT and Perplexity.
              </p>
            </Reveal>

            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              {SERVICES.map((c) => (
                <Reveal key={c.title}>
                  <div className="group relative h-full rounded-2xl border border-white/5 bg-[#1E293B]/50 p-8 backdrop-blur-sm transition-all duration-500 hover:-translate-y-2 hover:border-[#00D9FF]/40">
                    <div className="absolute inset-0 rounded-2xl bg-linear-to-br from-[#00D9FF]/0 to-[#00D9FF]/0 transition-all duration-500 group-hover:from-[#00D9FF]/10 group-hover:to-transparent" />
                    <div className="relative">
                      <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-xl border border-[#00D9FF]/20 bg-[#00D9FF]/10 transition-colors group-hover:bg-[#00D9FF]/20">
                        <c.icon className="h-7 w-7 text-[#00D9FF]" />
                      </div>
                      <h3 className="mb-3 text-xl font-bold text-white">{c.title}</h3>
                      <p className="leading-relaxed text-slate-400">{c.body}</p>
                    </div>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ── ABOUT ──────────────────────────────────────────────────────────── */}
        <section id="about" className="relative overflow-hidden bg-[#FAFAFA] py-20 md:py-28 lg:py-32">
          <div className="mx-auto max-w-6xl px-6 sm:px-8">
            <div className="grid items-center gap-16 lg:grid-cols-2 lg:gap-20">
              <Reveal className="relative">
                <div className="absolute -left-6 -top-6 h-32 w-32 rounded-2xl bg-[#00D9FF]/20 blur-2xl" />
                <div className="relative overflow-hidden rounded-3xl border border-[#0A0E27]/10 shadow-2xl">
                  {/* ⚠️ STOCK PHOTO — this is not Steven. Replace before this page ships. */}
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src="/sitedrop-founder.png"
                    alt="Web design consultant working on responsive website mockups at a desk with dual monitors"
                    className="h-full w-full object-cover"
                    width={1024}
                    height={1024}
                  />
                </div>
                <div className="absolute -bottom-6 -right-6 max-w-[220px] rounded-2xl border border-[#00D9FF]/20 bg-[#0A0E27] p-6 text-white shadow-xl">
                  <div className="mb-2 flex items-center gap-3">
                    <div className="h-2 w-2 animate-pulse rounded-full bg-[#00D9FF]" />
                    <span className="text-xs uppercase tracking-widest text-[#00D9FF]">
                      Available Now
                    </span>
                  </div>
                  <p className="text-sm text-slate-300">Booking projects for this quarter</p>
                </div>
              </Reveal>

              <Reveal>
                <span className="mb-6 inline-block rounded-full border border-[#0A0E27]/10 bg-[#0A0E27]/5 px-4 py-1.5 text-xs font-medium uppercase tracking-widest text-[#0A0E27]">
                  About the Founder
                </span>
                <h2 className="mb-6 text-4xl font-bold leading-tight text-[#0F172A] md:text-5xl lg:text-6xl">
                  Hi, I&rsquo;m{" "}
                  <span className="relative text-[#0A0E27]">
                    Steven James
                    <span className="absolute bottom-1 left-0 h-1 w-full bg-[#00D9FF]" />
                  </span>
                  .
                </h2>
                <p className="mb-6 text-lg leading-relaxed text-slate-600">
                  For over a decade, I&rsquo;ve helped local businesses stop losing customers to
                  competitors with better websites. What started as freelance code has grown into a
                  consultancy obsessed with one thing:{" "}
                  <strong className="text-[#0F172A]">building sites that actually make you money.</strong>
                </p>
                <p className="mb-8 text-lg leading-relaxed text-slate-600">
                  The web has changed. It&rsquo;s no longer enough to look good on desktop. Your
                  customers are on phones. They&rsquo;re searching Google. They&rsquo;re asking AI.
                  My mission is to make sure Steven James Consulting clients win on every one of
                  those battlegrounds — with strategy, craft, and code that ages beautifully.
                </p>

                <div className="mb-8 grid grid-cols-3 gap-6">
                  {[
                    { n: "10+", l: "Years Building" },
                    { n: "120+", l: "Sites Shipped" },
                    { n: "100%", l: "Hand-Coded" },
                  ].map((s) => (
                    <div key={s.l}>
                      <div className="text-3xl font-bold text-[#0A0E27]">{s.n}</div>
                      <div className="mt-1 text-xs uppercase tracking-widest text-slate-500">
                        {s.l}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="flex items-center gap-4 border-t border-[#0A0E27]/10 pt-6">
                  <div className="flex-1">
                    <div className="text-2xl italic text-[#0A0E27]">— Steven James</div>
                    <div className="mt-1 text-sm text-slate-500">Founder &amp; Lead Designer</div>
                  </div>
                  <a
                    href={PHONE_HREF}
                    className="inline-flex items-center gap-2 rounded-full bg-[#0A0E27] px-5 py-3 text-sm font-medium text-white transition-colors hover:bg-[#1E293B]"
                  >
                    <Phone className="h-4 w-4" />
                    Call Steven
                  </a>
                </div>
              </Reveal>
            </div>
          </div>
        </section>

        {/* ── PROCESS ────────────────────────────────────────────────────────── */}
        <section id="process" className="relative overflow-hidden bg-[#0A0E27] py-20 md:py-28 lg:py-32">
          <div className="absolute inset-0 opacity-10">
            <div className={`absolute inset-0 ${styles.grid60}`} />
          </div>

          <div className="relative z-10 mx-auto max-w-6xl px-6 sm:px-8">
            <Reveal className="mb-20 text-center">
              <span className="mb-6 inline-block rounded-full border border-[#00D9FF]/30 bg-[#00D9FF]/5 px-4 py-1.5 text-xs font-medium uppercase tracking-widest text-[#00D9FF]">
                The Process
              </span>
              <h2 className="mb-6 text-4xl font-bold text-white md:text-5xl lg:text-6xl">
                From Idea to Launch
                <br />
                <span className="text-[#00D9FF]">in Four Deliberate Steps</span>
              </h2>
              <p className="mx-auto max-w-2xl text-lg text-slate-400">
                A transparent, collaborative workflow. No mystery. No missed deadlines. Just a
                website you&rsquo;re proud to send customers to.
              </p>
            </Reveal>

            <div className="relative grid gap-6 md:grid-cols-2 lg:grid-cols-4 lg:gap-4">
              <div className="absolute left-[12.5%] right-[12.5%] top-16 hidden h-px bg-linear-to-r from-transparent via-[#00D9FF]/40 to-transparent lg:block" />
              {PROCESS.map((s) => (
                <Reveal key={s.n} className="relative">
                  <div className="relative h-full rounded-2xl border border-white/5 bg-[#1E293B]/60 p-8 backdrop-blur-sm transition-all duration-500 hover:-translate-y-2 hover:border-[#00D9FF]/40">
                    <div className="relative z-10 mb-6 flex h-14 w-14 items-center justify-center rounded-full bg-[#00D9FF] text-xl font-bold text-[#0A0E27]">
                      {s.n}
                    </div>
                    <s.icon className="mb-4 h-6 w-6 text-[#00D9FF]" />
                    <h3 className="mb-3 text-xl font-bold text-white">{s.title}</h3>
                    <p className="text-sm leading-relaxed text-slate-400">{s.body}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ── CONTACT ────────────────────────────────────────────────────────── */}
        <section
          id="contact"
          className="relative overflow-hidden py-20 md:py-28 lg:py-32"
          style={{ background: "linear-gradient(135deg, #0A0E27 0%, #1E293B 100%)" }}
        >
          <div className="absolute left-1/4 top-0 h-[500px] w-[500px] rounded-full bg-[#00D9FF] opacity-30 blur-[120px]" />
          <div className="absolute bottom-0 right-1/4 h-[400px] w-[400px] rounded-full bg-[#00D9FF] opacity-20 blur-[100px]" />
          <div className={`absolute inset-0 opacity-[0.03] ${styles.grid40}`} />

          <div className="relative mx-auto max-w-6xl px-6 sm:px-8">
            <div className="mb-14 text-center">
              <p className="mb-4 text-sm uppercase tracking-[0.3em] text-[#00D9FF]">
                Let&rsquo;s Build Something Great
              </p>
              <h2 className="mb-6 text-4xl font-bold text-white md:text-5xl lg:text-6xl">
                Get Your <span className="text-[#00D9FF]">Free Quote</span>
              </h2>
              <p className="mx-auto max-w-2xl text-lg leading-relaxed text-slate-300">
                Ready to launch a website that wins on mobile, Google, and AI search? Tell us about
                your project — we&rsquo;ll respond within 24 hours.
              </p>
            </div>

            <div className="grid items-start gap-8 lg:grid-cols-5">
              <div className="space-y-6 lg:col-span-2">
                {CONTACT_CARDS.map((c) => (
                  <div
                    key={c.label}
                    className="rounded-2xl border border-white/10 bg-white/5 p-6 shadow-2xl backdrop-blur-2xl transition-all duration-300 hover:border-cyan-400/30"
                  >
                    <div className="flex items-start gap-4">
                      <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#00D9FF]/15 text-[#00D9FF]">
                        <c.icon className="h-5 w-5" />
                      </div>
                      <div>
                        <p className="mb-1 text-xs uppercase tracking-wider text-slate-400">
                          {c.label}
                        </p>
                        {c.href ? (
                          <a
                            href={c.href}
                            className="text-lg font-semibold text-white transition-colors hover:text-cyan-400"
                          >
                            {c.value}
                          </a>
                        ) : (
                          <p className="text-lg font-semibold text-white">{c.value}</p>
                        )}
                      </div>
                    </div>
                  </div>
                ))}

                <div className="mt-8 hidden rounded-2xl border border-cyan-400/20 bg-linear-to-br from-cyan-400/10 to-transparent p-6 lg:block">
                  <div className="mb-3 flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-[#00D9FF]" />
                    <p className="text-xs uppercase tracking-wider text-[#00D9FF]">
                      What Happens Next
                    </p>
                  </div>
                  <ul className="space-y-2 text-sm text-slate-300">
                    <li className="flex items-start gap-2">
                      <span className="text-[#00D9FF]">01.</span> We review your project details
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-[#00D9FF]">02.</span> Schedule a discovery call
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-[#00D9FF]">03.</span> Receive a custom proposal
                    </li>
                  </ul>
                </div>
              </div>

              {/* The shared LeadForm block — same delivery path as every other site on the
                  platform, so a lead can never end up in the wrong inbox. Only the skin changes. */}
              <div className="lg:col-span-3">
                <LeadForm
                  source="/websites — SiteDrop design"
                  inColumn
                  theme="dark"
                  fields={[
                    { label: "Your Name", inputType: "text" },
                    { label: "Email Address", inputType: "email" },
                    { label: "Tell Us About Your Project", inputType: "text" },
                  ]}
                  buttonLabel="Send My Free Quote Request"
                  note="Your information is secure and never shared"
                  successHeading="Got it. I'll be in touch."
                  successBody={`We'll respond within 24 hours. If you'd rather not wait, call ${PHONE_DISPLAY}.`}
                />
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* ── FOOTER ─────────────────────────────────────────────────────────── */}
      <footer className="relative overflow-hidden bg-[#0A0E27]">
        <div className="absolute left-0 right-0 top-0 h-px bg-linear-to-r from-transparent via-cyan-400/50 to-transparent" />
        <div className="absolute -right-40 -top-40 h-96 w-96 rounded-full bg-[#00D9FF] opacity-10 blur-[120px]" />

        <div className="relative mx-auto max-w-6xl px-6 pb-8 pt-20 sm:px-8">
          <div className="mb-16 grid grid-cols-1 gap-12 md:grid-cols-2 lg:grid-cols-12">
            <div className="lg:col-span-5">
              <div className="mb-6 flex items-center gap-3">
                <div
                  className="flex h-11 w-11 items-center justify-center rounded-xl"
                  style={{ background: "linear-gradient(135deg, #00D9FF 0%, #0891b2 100%)" }}
                >
                  <Code2 className="h-6 w-6 text-[#0A0E27]" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white">Steven James</h3>
                  <p className="text-xs uppercase tracking-widest text-[#00D9FF]">Consulting</p>
                </div>
              </div>
              <p className="mb-6 max-w-md leading-relaxed text-slate-400">
                Building websites that win everywhere — mobile-first, Google-optimized, and ready
                for the AI search era. Premium web design consulting for businesses that mean
                business.
              </p>
            </div>

            <div className="lg:col-span-2">
              <h4 className="mb-5 text-sm font-semibold uppercase tracking-widest text-white">
                Services
              </h4>
              <ul className="space-y-3">
                {FOOTER_SERVICES.map((l) => (
                  <li key={l}>
                    <a
                      href="#services"
                      className="inline-block text-sm text-slate-400 transition-all duration-300 hover:-translate-y-0.5 hover:text-cyan-400"
                    >
                      {l}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            <div className="lg:col-span-2">
              <h4 className="mb-5 text-sm font-semibold uppercase tracking-widest text-white">
                Company
              </h4>
              <ul className="space-y-3">
                {FOOTER_COMPANY.map((l) => (
                  <li key={l.href + l.label}>
                    <a
                      href={l.href}
                      className="inline-block text-sm text-slate-400 transition-all duration-300 hover:-translate-y-0.5 hover:text-cyan-400"
                    >
                      {l.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            <div className="lg:col-span-3">
              <h4 className="mb-5 text-sm font-semibold uppercase tracking-widest text-white">
                Get In Touch
              </h4>
              <ul className="space-y-4">
                <li>
                  <a
                    href={PHONE_HREF}
                    className="group flex items-start gap-3 text-slate-400 transition-colors hover:text-white"
                  >
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-white/5 transition-colors group-hover:border-cyan-400/50">
                      <Phone className="h-4 w-4 text-[#00D9FF]" />
                    </div>
                    <div>
                      <p className="text-xs uppercase tracking-wider text-slate-500">Call</p>
                      <p className="text-sm font-medium">+1 210-851-4906</p>
                    </div>
                  </a>
                </li>
                <li>
                  <div className="flex items-start gap-3 text-slate-400">
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-white/5">
                      <MapPin className="h-4 w-4 text-[#00D9FF]" />
                    </div>
                    <div>
                      <p className="text-xs uppercase tracking-wider text-slate-500">Serving</p>
                      <p className="text-sm font-medium">Clients Nationwide</p>
                    </div>
                  </div>
                </li>
                <li>
                  <a
                    href="#contact"
                    className="group flex items-start gap-3 text-slate-400 transition-colors hover:text-white"
                  >
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-white/5 transition-colors group-hover:border-cyan-400/50">
                      <Mail className="h-4 w-4 text-[#00D9FF]" />
                    </div>
                    <div>
                      <p className="text-xs uppercase tracking-wider text-slate-500">Inquire</p>
                      <p className="text-sm font-medium">Send a Message</p>
                    </div>
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div
            className="relative mb-12 overflow-hidden rounded-2xl border border-white/10 p-8 md:p-10"
            style={{
              background:
                "linear-gradient(135deg, rgba(0, 217, 255, 0.08) 0%, rgba(30, 41, 59, 0.4) 100%)",
            }}
          >
            <div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#00D9FF] opacity-20 blur-[80px]" />
            <div className="relative flex flex-col items-center justify-between gap-6 md:flex-row">
              <div>
                <h3 className="mb-2 text-2xl font-bold text-white md:text-3xl">
                  Ready to launch your dream website?
                </h3>
                <p className="text-slate-300">Free consultation. No pressure. Just answers.</p>
              </div>
              <a
                href={PHONE_HREF}
                className="group inline-flex items-center gap-3 whitespace-nowrap rounded-xl bg-[#00D9FF] px-8 py-4 font-semibold text-[#0A0E27] shadow-lg transition-all duration-300 hover:scale-105 hover:shadow-cyan-400/50"
              >
                <Phone className="h-5 w-5" />
                Call Now
              </a>
            </div>
          </div>

          <div className="border-t border-white/10 pt-8 text-sm text-slate-500">
            <p>&copy; {new Date().getFullYear()} Steven James Consulting. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
