import { Render } from "@measured/puck";
import { config } from "@/components/puck/config";
import { seedFor } from "@/components/puck/seeds";
import { readPuckPublished } from "@/lib/puckContent";
import { WebsitesHeader, WebsitesFooter } from "@/components/websites/WebsitesChrome";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "A real website for your business — live in three days | Steven James Consulting",
  // ⚠️ NO PRICE HERE. Price comes up on the discovery call, not before it — and this description
  // is exactly what Google shows in results and what a texted link previews as, so a number here
  // reaches the prospect ahead of the conversation. Keep it about the outcome.
  description:
    "Built and live in three days. Your work, your reviews, your phone number — and a contact form that texts you the second someone fills it out. You never touch any of it.",
  alternates: { canonical: "/websites" },
  // ⚠️ THIS BLOCK IS LOAD-BEARING — without it Next.js inherits the ROOT layout's openGraph
  // wholesale, and a link texted to a groomer or a detailer previews as "Your AI Growth Partner."
  // That is the AI-implementation business, not this one. The title/description above do NOT
  // fill these in; og:* only ever comes from an openGraph block on the nearest segment.
  // The card image is generated by ./opengraph-image.tsx — leave `images` unset so it wins.
  openGraph: {
    title: "A real website for your business — live in three days",
    description:
      "Your work, your reviews, your phone number — and a contact form that texts you the second someone fills it out. You never touch any of it.",
    url: "https://www.stevenjamesconsulting.com/websites",
    siteName: "Steven James Consulting",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "A real website for your business — live in three days",
    description:
      "Your work, your reviews, your phone number — and a contact form that texts you the second someone fills it out.",
  },
};

// The bottom rung of the ladder: a plain, real website for a very small business. NOT the
// AI/Chloe offer and NOT a middle tier — no CRM, no automation, no tiers, no upgrade path shown.
// Ascension to the bigger offers happens on a phone call with Steven, never on this page.
//
// Every word here lives in the BUILDER, not in this file: edit at /edit/websites (and the header
// and footer at /edit/websites-nav and /edit/websites-footer). This route just renders whatever
// is published; before anything is published it renders the same seed the builder opens to, so
// the live page and the editor can never drift apart.
export default async function WebsitesPage() {
  const published = await readPuckPublished("websites");
  const data = published || seedFor("websites", "Websites");

  return (
    <>
      <WebsitesHeader />
      <main>
        <Render config={config} data={data} />
      </main>
      <WebsitesFooter />
    </>
  );
}
