// GENERATED by scripts/stamp-gs.mjs — do not edit by hand.
//
// What each Apps Script SHOULD be running, as a fingerprint of the file in this repo.
// /api/admin/check-scripts asks each live deployment what it is running and compares.
export const SCRIPT_VERSIONS: Record<string, string> = {
  "apply-webhook": "135e84b24148",
  "call-sheet": "c2124a24d7fa",
  "client-sheet": "9fbfa4fe6656",
  "sjc-sheets": "6e73691dc4f3"
};
