// Stamp each Apps Script with a fingerprint of its own contents, and generate the table the
// drift check compares against.
//
// ── THE FAILURE THIS EXISTS TO CATCH ──────────────────────────────────────────────────────────
// The .gs files in this repo are the source of truth for scripts that actually run inside Google.
// Nothing connects the two. You paste the file into script.google.com by hand, and a paste that
// never happened looks exactly like one that did.
//
// On 2026-08-05 that cost most of a day, twice. A timestamp fix was committed, "deployed", ran to
// Completed — and did nothing, because the live script was still an older version. Then a second
// attempt did the same. Both times the evidence said shipped and the sheet said otherwise.
//
// ── WHY THE FINGERPRINT IS DERIVED, NOT TYPED ────────────────────────────────────────────────
// A hand-written version number moves the problem: edit the file, forget to bump it, and the
// check passes while the code differs. So SCRIPT_VERSION is a hash of the file with its own
// version line blanked out. Change a single character anywhere and the expected value changes on
// its own — there is nothing to remember.
//
//   npm run stamp:gs    rewrite each SCRIPT_VERSION + regenerate lib/scriptVersions.ts
//   npm run check:gs    fail if any file's stamp is stale (i.e. edited but not re-stamped)
//
// The other half — whether the LIVE script matches — needs the deployment URLs, which are
// server-side secrets. That check lives at /api/admin/check-scripts.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const DIR = "scripts";
const MARK = "var SCRIPT_VERSION = ";

/**
 * The hash of a file with its own stamp line REMOVED — not blanked.
 *
 * ⚠️ Blanking it isn't idempotent, and the first run proved it: a file with no stamp yet hashes
 * differently from the same file with `SCRIPT_VERSION = ''` in it, so stamping immediately made
 * every stamp look stale. Deleting the line means an unstamped file and a stamped one hash
 * identically, which is the only way "run it twice, get the same answer" holds.
 */
export function fingerprint(source) {
  const withoutStamp = source.replace(/^var SCRIPT_VERSION = '.*';\n/m, "");
  return createHash("sha256").update(withoutStamp).digest("hex").slice(0, 12);
}

const files = readdirSync(DIR).filter((f) => f.endsWith(".gs"));
const check = process.argv.includes("--check");
const table = {};
let stale = [];

for (const file of files) {
  const path = join(DIR, file);
  const src = readFileSync(path, "utf8");
  const want = fingerprint(src);
  const has = (src.match(/^var SCRIPT_VERSION = '(.*)';$/m) || [])[1];
  table[file.replace(/\.gs$/, "")] = want;

  if (has === want) continue;
  if (check) {
    stale.push(`${file}: stamped ${has || "(none)"}, content says ${want}`);
    continue;
  }

  const stamped = has
    ? src.replace(/^var SCRIPT_VERSION = '.*';$/m, `${MARK}'${want}';`)
    : src.replace(/^(var [A-Z_]+ = )/m, `${MARK}'${want}';\n$1`);
  writeFileSync(path, stamped);
  console.log(`stamped ${file} -> ${want}`);
}

if (check) {
  if (stale.length) {
    console.error("Apps Script stamps are stale — run `npm run stamp:gs`:\n  " + stale.join("\n  "));
    process.exit(1);
  }
  console.log(`all ${files.length} Apps Script stamps current`);
} else {
  writeFileSync(
    "lib/scriptVersions.ts",
    `// GENERATED by scripts/stamp-gs.mjs — do not edit by hand.\n` +
      `//\n` +
      `// What each Apps Script SHOULD be running, as a fingerprint of the file in this repo.\n` +
      `// /api/admin/check-scripts asks each live deployment what it is running and compares.\n` +
      `export const SCRIPT_VERSIONS: Record<string, string> = ${JSON.stringify(table, null, 2)};\n`
  );
  console.log("wrote lib/scriptVersions.ts");
}
